[workspace]
members = [
	"booktyping",
	"booktyping-*",
]
resolver = "2"

[profile.release]
# Reduces the binary size of the WASM file.
lto = true
opt-level="z"

[workspace.dependencies]
clap = { version = "^4.5.4", features = ["derive"] }
v_utils = { version = "1.3.7", default-features = false, features = ["io"] }
dirs = "^5.0.1"
ratatui = { version = "^0.26.3", default-features = false, features = ["crossterm"]}
regex = "^1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "^1.0.117"
chrono = { version = "^0.4.38", features = ["serde"] }
deunicode = "^1.6.0"
