[package]
name = "booktyping"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["derive-new", "anyhow", "serde", "tokio"]

[dependencies]
derive-new = "^0.6.0"
anyhow = "^1.0.86"
# v_utils = { version = "^1.3.6", features = ["full"] }
clap = { version = "^4.5.4", features = ["derive"] }
v_utils = { version = "1.3.7", features = ["io"] }
