# Cornerstone options
unstable_features = true
hard_tabs = true
max_width = 155

# Experimental
format_strings = false
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
# attr_fn_like_width = 150
